name: Build Repo

on:
  workflow_dispatch:
    inputs:
      repo:
        required: true
      branch:
        default: 'main'

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Hello ${{github.event.inputs.repo}}"
