name: Build Repo

on:
  workflow_dispatch:
    inputs:
      repo:
        required: true
      branch:
        default: 'main'

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.2.0
    - uses: actions/setup-python@v3.0.0
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64'
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '17'
    - name: Build & Publish
      run: bash <(curl -s https://raw.githubusercontent.com/u9g/repopublisher/main/.github/workflows/downloader.sh)
      env:
        REPO: ${{github.event.inputs.repo}}
        BRANCH: ${{github.event.inputs.branch}}
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
